---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  tslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.ts"
  - "**.tsx"
exclude_paths:
- node_modules/
- client/node_modules/
